export {
  getDatabase,
  closeDatabase,
  getProfiles,
  getProfile,
  createProfile,
  updateProfile,
  deleteProfile,
  checkProfileGuardrail,
  upsertMedia,
  addFavorite,
  removeFavorite,
  getFavorites,
  isFavorite,
  addSaved,
  removeSaved,
  getSaved,
  isSaved,
  updateWatchProgress,
  getWatchProgress,
  getContinueWatching,
  addWatchHistory,
  getWatchHistory,
  getSetting,
  setSetting,
  setActiveProfileId,
  getActiveProfileId,
  verifyPin,
  verifyPassword,
  updateProfileSecurity,
  addDownload,
  updateDownload,
  getDownloads,
  getDownload,
  deleteDownload,
  getActiveDownloads,
} from './database';

export {
  buildKidsFilterParams,
  isContentAppropriateForKids,
  getCertificationOrder,
  getKidsFilterForCountry,
  KIDS_ALLOWED_CERTIFICATIONS,
} from './age-rating';

export { acquireSlot, releaseSlot, getQueueStatus } from './tmdb-queue';
